"""empty message

Revision ID: b4b7f49adc81
Revises: d398eb59c262
Create Date: 2018-02-27 11:23:06.670566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b7f49adc81'
down_revision = 'd398eb59c262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('serial_no', sa.String(), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_manager_id'), 'accounts', ['manager_id'], unique=False)
    op.create_index(op.f('ix_accounts_serial_no'), 'accounts', ['serial_no'], unique=False)
    op.create_index(op.f('ix_accounts_title'), 'accounts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_title'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_serial_no'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_manager_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
